= Nextcloud Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Nextcloud: https://nextcloud.com/[Nextcloud]

Configuration for my {Nextcloud} server.

These are configuration files for my Nextcloud server, which is run via several containers.
See the https://github.com/jwillikers/home-lab-helm[home-lab-helm] repository for the containers' configuration.
Environment variables defined in that configuration cover most of the Nextcloud configuration. 
A couple of files are still required, so they are kept here.

== Usage

The files provided in the `etc` subdirectory are meant to be mounted inside the Nextcloud container under the `/usr/local` directory.
The subdirectory `docker-entrypoint-hooks.d/pre-installation` should be mounted under the root of the container, where it will be executed before installation.
The hook just concatenates the `/var/www/html/autoconfig.php` with the included `autoconfig.php` file.
This file includes configuration for things that are not configured automatically through environment variables in the container.
The home-lab-helm Kubernetes configuration expects this repository to be in a specific location.
Follow these instructions to put the files in the expected location.

. Create the `~/Projects` directory.
+
[,sh]
----
mkdir -p ~/Projects
----

. Clone this repository under the `~/Projects` directory.
+
[,sh]
----
git -C ~/Projects clone https://github.com/jwillikers/nextcloud-config.git
----

== References

.Documentation
* https://github.com/h2non/imaginary[imaginary]
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/automatic_configuration.html[Nextcloud Admin Manual: Automatic setup]
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html[Nextcloud Admin Manual: Background jobs]
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#deleted-items-trash-bin[Nextcloud Admin Manual: Configuration Parameters - Deleted Items (trash bin)]
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/email_configuration.html[Nextcloud Admin Manual: Email]
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/index.html[Nextcloud Admin Manual: Nextcloud configuration]
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html[Nextcloud Admin Manual: Reverse proxy]
* https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#previews[Nextcloud Admin Manual: Server tuning - Previews]
* https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#tune-php-fpm[Nextcloud Admin Manual: Server tuning - Tune PHP-FPM]
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html[Nextcloud Admin Manual: Transactional file locking]
* https://github.com/nextcloud/docker[Nextcloud Docker]
* https://hub.docker.com/_/redis[redis Official Docker Image] 

.See Also
* https://github.com/nextcloud/all-in-one[Nextcloud All-in-One]

== Code of Conduct

The project's Code of Conduct is available in the link:CODE_OF_CONDUCT.adoc[] file.

== License

This project is licensed under the https://creativecommons.org/licenses/by-sa/4.0/legalcode[Creative Commons Attribution-ShareAlike 4.0 International License].

© 2023 Jordan Williams

== Authors

mailto:{email}[{author}]

