$AUTOCONFIG = array(
  'filelocking.enabled' => true,
  'default_phone_region' => 'US',
  'enabledPreviewProviders' => [
    'OC\Preview\BMP',
    'OC\Preview\GIF',
    'OC\Preview\Imaginary',
    'OC\Preview\JPEG',
    'OC\Preview\Krita',
    'OC\Preview\MarkDown',
    'OC\Preview\Movie',
    'OC\Preview\MP3',
    'OC\Preview\OpenDocument',
    'OC\Preview\PNG',
    'OC\Preview\SVG',
    'OC\Preview\TXT',
    'OC\Preview\XBitmap',
  ],
  'preview_format' => 'webp',
  'preview_imaginary_url' => 'http://localhost:8088',
  'preview_max_filesize_image' => 100,
  'preview_max_memory' => 4096,
  'preview_max_x' => null,
  'preview_max_y' => null,
  'trashbin_retention_obligation' => '7, 30',
);
